# Generated by Django 4.2.2 on 2023-06-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20, null=True),
        ),
    ]
